# Generated by Django 3.1 on 2020-10-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0002_auto_20201008_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasttweetid',
            name='tweetId',
            field=models.CharField(max_length=100),
        ),
    ]
